amcl:
  ros__parameters:
    bond_disable_heartbeat_timeout: true
    alpha1: 0.2  # 0.2
    alpha2: 0.2  # 0.2
    alpha3: 2.0  # 0.2
    alpha4: 2.0  # 0.2
    alpha5: 0.2  # 0.2
    always_reset_initial_pose: false  # false(default)
    base_frame_id: base_link  # base_footprint(default)
    beam_skip_distance: 0.5  # 0.5
    beam_skip_error_threshold: 0.9  # 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    initial_pose:
      x: 0.01
      y: 0.01
      yaw: 0.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 3.0  # 2.0(default)
    laser_max_range: 120.0  # 100.0(default)
    laser_min_range: 5.0  # -1.0(default)
    laser_model_type: likelihood_field
    map_topic: map
    max_beams: 100  # 60(default)
    max_particles: 3000  # 2000(default)
    min_particles: 1000  # 500(default)
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1  # 0.0
    recovery_alpha_slow: 0.001  # 0.0
    resample_interval: 1  # 1
    robot_model_type: nav2_amcl::DifferentialMotionModel  # nav2_amcl::DifferentialMotionModel
    save_pose_rate: 10.0  # 0.5
    scan_topic: scan
    set_initial_pose: true  # false(default)
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0  # 1.0
    update_min_a: 0.2
    update_min_d: 1.0  # 0.25
    use_sim_time: false
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
