make_dir_node:
  ros__parameters:
    ws_path: whill2_ws
    place_path: nakanoshima
    date_path: "2023_10_13_2"
    bag_path: bag
    map_path: map
    waypoint_path: waypoint
    branchpoint_path: branchpoint
    rewaypoint_path: rewaypoint
    remap_path: remap_path
    bag_name: bag_0.db3
    map_name: map
    remap_name: remap.yaml
    waypoint_name: waypoint.txt
    rewaypoint_name: rewaypoint.txt
