kuaro_whill_launch:
    whill_joy_state: 'whill/states/joy'
    whill_joy_control: 'whill/controller/joy'
    ros2_whill_cmd_vel: 'whill/controller/cmd_vel'
    whill_joy2_cmd_vel: 'whill_joy2/cmd_vel'